### ISSUE TITLE
srt unmatch content

### ISSUE THREAD

**Issue by alexmaehon** [sinedie/SRT-DeepL-Translator#17]
Traceback (most recent call last):
  File "srt_trans.py", line 28, in <module>
    driver=chrome_driver
  File "C:\Users\T.H. Long\.conda\envs\tf2.0\lib\site-packages\srt_deepl\main.py", line 131, in translate
    wrap_limit,
  File "C:\Users\T.H. Long\.conda\envs\tf2.0\lib\site-packages\srt_deepl\deepl.py", line 63, in translate
    subs = open_srt(file_path)
  File "C:\Users\T.H. Long\.conda\envs\tf2.0\lib\site-packages\srt_deepl\srt_parser.py", line 10, in open_srt
    subs = list(srt_file)
  File "C:\Users\T.H. Long\.conda\envs\tf2.0\lib\site-packages\srt.py", line 349, in parse
    _check_contiguity(srt, expected_start, actual_start, ignore_errors)
  File "C:\Users\T.H. Long\.conda\envs\tf2.0\lib\site-packages\srt.py", line 406, in _check_contiguity
    raise SRTParseError(expected_start, actual_start, unmatched_content)
srt.SRTParseError: Expected contiguous start of match or end of input at char 0, but started at char 1 (unmatched content: '锘')

**Comment by tssajo** [comment]
This is happening because the input srt file has a BOM at the very beginning of the file. What is a BOM? See:
https://en.wikipedia.org/wiki/Byte_order_mark
BOM can be present at the beginning of UTF8 encoded files. So to fix this, we should open all files as if they were UTF8 encoded. (If the input file is plain English then it won't make any difference anyway besides fixing this possible issue.)
I suggested a fix to this in my last comment here:
https://github.com/sinedie/SRT-DeepL-Translator/issues/18

**Comment by sinedie** [comment]
As tssajo said, it is fixed with PR #20. Reopen if issue persist
