### ISSUE TITLE
choose_languages error again

### ISSUE THREAD

**Issue by alexmaehon** [sinedie/SRT-DeepL-Translator#23]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pywebio/session/threadbased.py", line 86, in main_task
    target()
  File "/content/app.py", line 1551, in main
    delete_old=True,
  File "/content/app.py", line 266, in translate
    wrap_limit,
  File "/content/app.py", line 134, in translate
    self.choose_languages(lang_from, lang_to)
  File "/content/app.py", line 117, in choose_languages
    f"//button[@dl-test='translator-lang-option-{lang_from['lang'].lower()}'] | //button[text()='{lang_from['description']}']",
  File "/content/app.py", line 51, in __init__
    WebDriverWait(driver, 60).until(lambda driver: find_element(*locator))
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55bfb3b0b1a3 <unknown>
#1 0x55bfb38d7ac3 <unknown>
#2 0x55bfb390f869 <unknown>
#3 0x55bfb390fa41 <unknown>
#4 0x55bfb39436e7 <unknown>
#5 0x55bfb392d10d <unknown>
#6 0x55bfb39413cc <unknown>
#7 0x55bfb392d443 <unknown>
#8 0x55bfb390348b <unknown>
#9 0x55bfb3904975 <unknown>
#10 0x55bfb3b872a0 <unknown>
#11 0x55bfb3b4281a <unknown>
#12 0x55bfb3b4234a <unknown>
#13 0x55bfb3b42e75 <unknown>
#14 0x55bfb3b8314b <unknown>
#15 0x55bfb3b431de <unknown>
#16 0x55bfb3b24c23 <unknown>
#17 0x55bfb3b4d6b8 <unknown>
#18 0x55bfb3b4d852 <unknown>
#19 0x55bfb3b66b60 <unknown>
#20 0x7fba1a32b6db <unknown>

**Comment by alexmaehon** [comment]
**In another machine:**

Traceback (most recent call last):
  File "/home/babel/.local/lib/python3.8/site-packages/pywebio/session/threadbased.py", line 86, in main_task
    target()
  File "app.py", line 1403, in main
    translate(
  File "app.py", line 260, in translate
    subs = translator.translate(
  File "app.py", line 132, in translate
    self.choose_languages(lang_from, lang_to)
  File "app.py", line 112, in choose_languages
            Button(
            self.driver,
            "XPATH",
            f"//button[@dl-test='translator-lang-option-{lang_from['lang'].lower()}'] | //button[text()='{>
        ).click()

  File "app.py", line 50, in __init__
    WebDriverWait(driver, 60).until(lambda driver: find_element(*locator))
  File "/home/babel/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55b33b5c2bb3 <unknown>
#1 0x55b33b3df21a <unknown>
#2 0x55b33b41671a <unknown>
#3 0x55b33b4168f1 <unknown>
#4 0x55b33b44ee24 <unknown>
#5 0x55b33b43573d <unknown>
#6 0x55b33b44cb25 <unknown>
#7 0x55b33b435603 <unknown>
#8 0x55b33b4097a5 <unknown>
#9 0x55b33b40a941 <unknown>
#10 0x55b33b607186 <unknown>
#11 0x55b33b609714 <unknown>
#12 0x55b33b609e56 <unknown>
#13 0x55b33b5f0f4e <unknown>
#14 0x55b33b60a49c <unknown>
#15 0x55b33b5e5782 <unknown>
#16 0x55b33b624f58 <unknown>
#17 0x55b33b6250e9 <unknown>
#18 0x55b33b63ef08 <unknown>
#19 0x7fac4705a609 <unknown>

**Comment by alexmaehon** [comment]
Button(
self.driver,
"XPATH",
f"//button[@DL-test='translator-lang-option-{lang_from['lang'].lower()}'] | //button[text()='{>
).click()

**Comment by alexmaehon** [comment]
some work on other file

**Comment by sinedie** [comment]
@alexmaehon I guess you manage to make it work... If not, reopen and tell what the problem was XD.

Pd: I know I've been a little too far from this repo, but im comming back
